### ISSUE TITLE
Otherworld Concept Progress Tracker

### ISSUE THREAD

**Issue by DeveloperWOW64** [DepthCDLS/Otherworld#1]
<h1/> <img src="https://user-images.githubusercontent.com/71598437/194718448-4f82f6d0-2530-425d-aa8b-16af43746c10.svg" width="30"/> Otherworld Concept Progress Tracker

### 🖼️ Iconography

- [ ] Finish Logo
  - [x] Remake Logo to represent rebrand
  - [x] Make logo fluent
  - [ ] Make logo in PNG format
  - [ ] Attribute to Icons8 for logo creation 
---
Previously: 
<img src="https://user-images.githubusercontent.com/71598437/194718609-13af54ef-2d94-4173-a5af-23bc91d8642b.png" width="100"/>
Now: 
<img src="https://user-images.githubusercontent.com/71598437/194718448-4f82f6d0-2530-425d-aa8b-16af43746c10.svg" width="100"/>

###### Work In Progress

```
Protocol is a different dimension seperated by a wall called the 'Star of Magnolia'.
However, a small shard broke off the Star of Magnolia, appropriately named the 'Shard'.
There are different planets and they each have different beliefs of how that Shard created the world. 
These planets are actually seperate VS projects that make one large solution, and they must be built and started individually as they are actually seperate videogames. 
The planets or videogames include: Otherworld, Cube, Area, Heaven, and others I cannot think of at this moment.
The 'Kingdom of Otherworld' believe that the Shard transformed into a being named the 'Jellymouse' who created other beings or 'Gods' that channeled Jellymouse's power individually. 
Most of the Gods got along with eachother, except for the God of Life and the God of Death (sometimes known as the God of Murder).
The God of Life kept creating more beings but the God of Murder kept killing them because he thought they were too ugly.
Eventually, the God of Life created a creature by accident that looked to some like an animal, and to some a different species of human. 
Before the God of Murder could eliminate this creature, Jellymouse, along with the God of Shapeshifting, stopped him. 
The God of Shapeshifting (one of the more powerful gods) cursed both the God of Life and the God of Murder to one singular being, that would balance eachother out, representing a Yin and Yang. 
Jellymouse ordered them to create more of this balanced, 'accidental' creature, as they were beautiful. 
They had created two beings, both male. 
The first one the God of Life had created was named 'Jeffrey' and the second 'Zeus'. 
Time was not possible in the state of creation the Protocol was in, and therefore no-one can truly calculate how long it took for this Creation to go on, however some Otherworld scientists have argued that it took about two years.
```

### 🙋 Characters

See the [`Assets Database`](https://lists.live.com/:l:/g/personal/d8c081a789b2526e/FCV19slqF2ZAqw7WG0kO8r4Bsz7aTC5LWwZ1fyvOBA2S2w?e=Ep7ZPn) for info on characters.
The characters may be subject to change and also may be deleted in favour of the ability for the user to create their own characters.

### 🖋️ Game Art

In the final release, Otherworld characters will look somewhat like [`Nintendo`](https://github.com/Nintendo)'s Miis
The Mii Art (DS/Switch) is shown below:
#### Andrex Andrex:

Switch:
![AndrexNew](https://user-images.githubusercontent.com/71598437/194719576-b936ee45-7534-4d46-be7f-290102860d9c.png)

DS:
![Andrex](https://user-images.githubusercontent.com/71598437/194719618-fcfeda72-21e7-47e6-bfed-04fce5d41aa9.JPG)
![AndrexFull](https://user-images.githubusercontent.com/71598437/194719623-634b79da-a62e-4077-9136-cf819a2cf4d2.JPG)

#### Mary Andrex

DS:
![Mary](https://user-images.githubusercontent.com/71598437/194719635-1fe7be71-3272-4497-96fd-0daddffa951c.JPG)
![MaryFull](https://user-images.githubusercontent.com/71598437/194719643-53b39032-1e25-4661-a440-c2eb40358a9d.JPG)

#### Samson Starlight

Switch:
![SamsonNew](https://user-images.githubusercontent.com/71598437/194719804-8954985a-85bd-426b-8adb-27b553a1a186.png)

#### Samson Succulent-Star (sometimes L. Samson/Lord of Samsons)

Switch:
![LSamsonNew](https://user-images.githubusercontent.com/71598437/194719850-896bc52e-eb55-4b3d-838d-234b03af032e.png)

**Comment by Lamparter** [comment]
See @lazycoder747 (aka @thatcoderguy877)'s comment on the @RiversideValley discord server, Crescent:
> If we ever have a game that costs money...
> ```html
> <p>Hi! Nice to meet you!&nbsp;</p>
> <p>Your probably thinking "What is this screen telling me?" "I wanna play my&nbsp;<strong>PIRATED&nbsp;</strong>game!"</p>
> <p>Well, about that...</p>
> <p>You did something quite naughty...</p>    
> <p>You have to be nice...</p>
> <p>And&nbsp;<strong>PAY&nbsp;</strong>for the game...</p>
> <p>You think that you can use this?</p>
> <p>Well...</p>    
> <p><strong>NOW IT'S LOCKED</strong></p> 
> <p><strong>YOU CAN NO LONGER USE THIS INSTALLATION OF THIS GAME!</strong></p>
> <p>Let me be a little nicer...</p>
> <p>You need to get out that credit/debit card out now...</p>     
> <p>Because I need that money...</p>
> <p>And I have a whole team to help...</p>
> <p>And I can't do that if you don't&nbsp;<strong>PAY!</strong></p> 
> <ol>
> <ol>
> <li>Get your card ready.</li>
> <li>Go to our website and pay the money required.</li>
> <li>Re-install this game</li>
> <li>Use the one-time lisense key that you have been shown. eg. XXXX-XXXXX-XXX-XX-X-XXX</li>
> <li>Enjoy your&nbsp;<strong>NON-PIRATED&nbsp;</strong>game.</li>
> <li>Don't do that again.</li>
> </ol>
> </ol>
> <p><strong>Understood?</strong></p>
>       <p><strong>GOOD!<p>
>         <p><strong>Now go and follow the instructions!
>           <p>HEY!
>             <p>GO!
>               <p>NOW!
>                 <p>Please?
>                   <p>Pay for the game!
>                     <p>PLEASE!
>                      <p>OK! You won...
>                        <p>But still no game for you!
> ```
> <p>Hi! Nice to meet you!&nbsp;</p>
> <p>Your probably thinking "What is this screen telling me?" "I wanna play my&nbsp;<strong>PIRATED&nbsp;</strong>game!"</p>
> <p>Well, about that...</p>
> <p>You did something quite naughty...</p>    
> <p>You have to be nice...</p>
> <p>And&nbsp;<strong>PAY&nbsp;</strong>for the game...</p>
> <p>You think that you can use this?</p>
> <p>Well...</p>    
> <p><strong>NOW IT'S LOCKED</strong></p> 
> <p><strong>YOU CAN NO LONGER USE THIS INSTALLATION OF THIS GAME!</strong></p>
> <p>Let me be a little nicer...</p>
> <p>You need to get out that credit/debit card out now...</p>     
> <p>Because I need that money...</p>
> <p>And I have a whole team to help...</p>
> <p>And I can't do that if you don't&nbsp;<strong>PAY!</strong></p> 
> <ol>
> <ol>
> <li>Get your card ready.</li>
> <li>Go to our website and pay the money required.</li>
> <li>Re-install this game</li>
> <li>Use the one-time lisense key that you have been shown. eg. XXXX-XXXXX-XXX-XX-X-XXX</li>
> <li>Enjoy your&nbsp;<strong>NON-PIRATED&nbsp;</strong>game.</li>
> <li>Don't do that again.</li>
> </ol>
> </ol>
> <p><strong>Understood?</strong></p>
>       <p><strong>GOOD!<p>
>         <p><strong>Now go and follow the instructions!
>           <p>HEY!
>             <p>GO!
>               <p>NOW!
>                 <p>Please?
>                   <p>Pay for the game!
>                     <p>PLEASE!
>                      <p>OK! You won...
>                        <p>But still no game for you!

###### `https://discord.com/channels/1034024652844044318/1034024653787779092/1060630077882237040`
###### `https://discord.com/channels/1034024652844044318/1034024653787779092/1060629614935945288`

###### Also see `https://www.youtube.com/watch?v=EaV0XpBB-yo` (@nintendo animal crossing pirated scenes) and `https://www.youtube.com/watch?v=lolTpMkBiHo` (@nintendo miitopia pirated scenes)
